### PR TITLE
stompest.simple: transactions added, logger removed

### PR DESCRIPTION
**Pull request by nikipore**
- added transaction handling (incl. context manager and unit tests)
- removed logger from stompest.simple.Stomp (I believe it breaks the simplicity and logging should be up to the user)

### CODE REVIEW

**Comment by theduderog** [comment]
Thank you.

**Comment by theduderog** [comment]
Thank you.  Are you planning to add this for Twisted as well?

On Fri, Jun 22, 2012 at 6:20 PM, nikipore <
reply@reply.github.com

**Comment by nikipore** [comment]
It's my pleasure. Sorry for the projrct files. I can add that to Twisted as well, but I'm a bit busier for the next weeks (making an application using stompest fly), so that might take a while. And I still need to gain speed on Twisted.

How would you schedule a stop() of a Twisted client? Something like

reactor.callLater(self.runTimeInSeconds, reactor.stop)

but with cleaning up any stomp connection(s) via stomp.disconnect(). The stomp connection is only available to the handlers, not to the client itself. What does one do when there is more than one connection?

Am 25.06.2012 um 18:34 schrieb Roger Hoover:

**Comment by theduderog** [comment]
No problem.  There's no one asking for transactions in the Twisted client.
 I'm was just wondering.

You get the stomp connection back from the connect() call as well as in
handlers so you can keep it around.

stomp = StompCreator.getConnection()

...

#Scheduling a stop
yield stomp.getDisconnectedDeferred()
reactor.stop()

On Mon, Jun 25, 2012 at 10:42 AM, nikipore <
reply@reply.github.com

**Pull request merged**
